timezone: Asia/Tokyo
lang: ja_JP
title: 株式会社 Nizitsuku
description: > # ignore newlines
  二次創作がより多くなされることは、
  その作品をより豊かにするという理念のもと、
  二次創作を通してクリエイターが刺激し合い、
  作品全体の質を高めていくことができるプラットフォームを提供します。
permalink: /:title
google_site_verification: 
google_analytics: 
plugins:
  - jekyll-sitemap
