lang: ja_JP
title: 駆逐艦菊月会
description: > # ignore newlines
  駆逐艦「菊月」の元乗員およびその遺族、
  関係者で構成される戦友会です。
  一切の政治的思想に与せず、
  戦没または物故した「菊月」元乗員の慰霊、
  会員の親睦や情報共有を行い、
  「菊月」の軌跡や資料を後世に伝えることを目的としています。
permalink: /:title
